<h1>Seznam článků</h1>
<div class="table-responsive-md">
    <table class="table table-striped">
    <?php foreach ($clanky as $clanek) : ?>
        <tr>
            <th>Článek</th><th>publikovaný/nepublikovaný</th>
        </tr>
            <td>
                <h2><a href="clanek/<?= $clanek['url'] ?>"><?=$clanek['titulek'] ?></a></h2>
                <?= $clanek['popisek'] ?>
                <br /><br>
                
                <a class="odsazeniautor" href="editor/<?= $clanek['url'] ?>">Editovat</a>
                <a class="odsazeniautor" href="clanek/<?= $clanek['url'] ?>/odstranit">Odstranit</a>
            </td>
            <td style="padding-top:50px;">
                <?php if($clanek['publikovani']) {echo("publikovano"); ?>
                <?php } else{ echo("nepublikovano");} ?>
            </td>
        </tr>
    <?php endforeach ?>
    </table>
</div>