<h1>Seznam článků</h1>
<table class="table table-striped">
<?php foreach ($clanky as $clanek) : ?>
    <tr>
        <td>
            <h2><a href="clanek/<?= $clanek['url'] ?>"><?= $clanek['titulek'] ?></a></h2>
            <?= $clanek['popisek'] ?>
            <?php if ($admin) : ?>
                <br />
                <a href="editor/<?= $clanek['url'] ?>">Editovat</a>
                <a href="clanek/<?= $clanek['url'] ?>/odstranit">Odstranit</a>
                <a href="clanek/<?= $clanek['url'] ?>/publikuj">publikuj</a>
            <?php endif ?>
        </td>
    </tr>
<?php endforeach ?>
</table>