<h1>Editor článků</h1>

<form method="post" enctype="multipart/form-data">
    <input type="hidden" name="clanky_id" value="<?= $clanek['clanky_id'] ?>" />
    Titulek<br />
    <input type="text" name="titulek" value="<?= $clanek['titulek'] ?>" /><br />
    URL<br />
    <input type="text" name="url" value="<?= $clanek['url'] ?>" /><br />
    Popisek<br />
    <input type="text" name="popisek" value="<?= $clanek['popisek'] ?>" /><br />
    Klíčová slova<br />
    <input type="text" name="klicova_slova" value="<?= $clanek['klicova_slova'] ?>" /><br />
    Soubor pdf <br>
    <input type="file" accept=".pdf" name="soubor" id="soubor"><br>
    Obsah
    <textarea name="obsah"><?= $clanek['obsah'] ?></textarea><br>
    <input type="submit" value="Uložit článek" name="submit" />
</form>

<script src="https://cdn.ckeditor.com/ckeditor5/24.0.0/decoupled-document/ckeditor.js"></script>
<script>
   CKEDITOR.replace('obsah');
</script>