        </main>
        <footer>
            <div class="main_footer container-fluid py-5 bg-secondary">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-12">
                            <h3>Redakce Smile</h3>
                            <p class="text-white">Jedna se o jedinečnou redakci, kde naleznout mnoho zajimavých článků ze všech monžných kategorií.<br>Od sportovních článků až po politické i když těch zde je spíše méně než více.<br>Každý zde nalezne to své a něco nového se dočte.</p>
                        </div>
                        <div class="col-md-6 col-12">
                            <h3>Kontaktní údaje</h3>
                            <p class="text-white">Pokud by nastal nějaký problém nevahejte kotaktovat.<br>Email: <a class="footerlink" href="mailto:Cifka.D@seznam.cz">Cifka.D@seznam.cz</a><br>Adresa: Borsky park 14/Plzeň</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright container-fluid bg-dark py-3">
                <div class="container text-center">
                    <p class="text-white mb-0">Developed by Daniel Cífka</p>
                </div>
            </div>
        </footer>    
        <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    </body>
</html>