<!DOCTYPE html>
<html lang="cs-cz">
  <head>
    <base href="/localhost" />
    <title><?= $titulek ?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="myStyle.css" type="text/css">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href=<?=$_SESSION['home_page']?>>
            <img src="obrazky/favicon.ico" class="picture"/>Redakce Smile</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="uvod">Úvod</a>
                <a class="nav-link active" href="clanek">Publikované články</a>
                <a class="nav-link active" href="prihlaseni">Přihlášení</a>
            </div>
            </div>
        </div>
    </nav>
    <main>