<!DOCTYPE html>
<html lang="cs-cz">
  <head>
    <base href="/localhost" />
    <title><?= $titulek ?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="myStyle.css" type="text/css">
    <link rel="icon" href="obrazky/favicon.ico">
    <script src="//cdn.ckeditor.com/4.15.1/full/ckeditor.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="uvod">
                <img src="obrazky/favicon.ico" alt="Ikona" class="picture"/>Redakce Smile
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="uvod">Úvod</a>
                <a class="nav-link active" href="clanek">Seznam Článků</a>
                <a class="nav-link active" href="administracerecenzent">Profil</a>
                <a class="nav-link active" href="administraceadmin/odhlasit">Odhlášení</a>
            </div>
            </div>
        </div>
    </nav>
    <main>