<h1>Přihlášení</h1>

<form method="post">
    <label for="Login" class="d-block">Login:</label>
    <input type="text" id="Login" name="Login" class="col-auto mb-4" required/>
    <label for="Heslo" class="d-block">Heslo:</label>
    <input type="password" id="Heslo" name="heslo" class="col-auto mb-4" required/>
    <input type="submit" value="Přihlásit" class="btn btn-primary d-block mx-auto"/>
</form>
<br>

<p style="padding-bottom:30px;">Pokud ještě nemáte účet, <a href="registrace" class="link">zaregistrujte se</a>.</p>