<h1>Seznam recenzí</h1>
<table class="table table-striped">
    <tr>
        <th>titulek</th><th>hodnoce</th><th>autor</th><th>datum</th>
    </tr>
    <?php foreach ($recenze as $hodnoceni) : ?>
    <tr>
        <td>
        <a href="recenze/<?= $hodnoceni['titulek'] ?>"><?= $hodnoceni['titulek'] ?>
        </td>
        <td>
            <?= $hodnoceni['hodnoceni'] ?>
        </td>
        <td>
            <?= $hodnoceni['autor'] ?>
        </td>
        <td>
            <?= $hodnoceni['datum'] ?>
        </td>
    </tr>
<?php endforeach ?>
</table>
