<?php foreach ($recenze as $hodnoceni) : ?>
<h1>Seznam recenzí <?= $hodnoceni['titulek'] ?></h1>
<?php endforeach ?>
<table class="table table-striped">
    <tr>
        <th>titulek</th><th>hodnoce</th><th>autor</th><th>datum</th>
    </tr>
    <?php foreach ($recenze as $hodnoceni) : ?>
    <tr>
        <td>
            <?= $hodnoceni['titulek'] ?>
        </td>
        <td>
            <?= $hodnoceni['hodnoceni'] ?>
        </td>
        <td>
            <?= $hodnoceni['autor'] ?>
        </td>
        <td>
            <?= $hodnoceni['datum'] ?>
        </td>
    </tr>
<?php endforeach ?>
</table>

<a href="recenze/<?= $hodnoceni['titulek'] ?>/publikuj"><button type="button" class="btn btn-primary">Publikuj</button></a>