<h1>Registrace</h1>

<form method="post">
    <label for="Login" class="d-block">Login:</label>
    <input type="text" id="Login" name="login" class="col-auto mb-4" required/>
    <label for="Jmeno" class="d-block">Jméno:</label>
    <input type="text" id="Jmeno" name="jmeno"class="col-auto mb-4" required />
    <label for="Prijmeni" class="d-block">Příjmení:</label>
    <input type="text" id="Prijmeni" name="prijmeni" class="col-auto mb-4" required/>
    <label for="Email" class="d-block">Email:</label>
    <input type="email" id="Email" name="email" class="col-auto mb-4" required/>
    <label for="Heslo" class="d-block">Heslo:</label>
    <input type="password" id="Heslo" name="heslo" class="col-auto mb-4" required/>
    <label for="Heslo2" class="d-block">Heslo znovu:</label>
    <input type="password" id="Heslo2" name="heslo_znovu" class="col-auto mb-4" required/>
    <label for="Rok" class="d-block">Rok:</label>
    <input type="number" id="Rok" name="rok" class="col-auto mb-4" required/>
    <input type="submit" class="btn btn-primary d-block mx-auto" value="Registrovat" />
</form>