<h1>Registrace</h1>

<form method="post">
    Login<br />
    <input type="text" name="login" /><br />
    Jméno<br />
    <input type="text" name="jmeno" /><br />
    Příjmení<br />
    <input type="text" name="prijmeni" /><br />
    E-mail<br />
    <input type="email" name="email" /><br />
    Heslo<br />
    <input type="password" name="heslo" /><br />
    Heslo znovu<br />
    <input type="password" name="heslo_znovu" /><br />
    Aktuální rok<br />
    <input type="number" name="rok"/><br />
    <input type="submit" value="Registrovat" />
</form>