<h1>Seznam uživatelů</h1>
<table class="table table-striped">

    <tr>
        <th>Login</th><th>Jméno</th><th>Příjmení</th><th>Email</th><th>Oprávnění</th><th>odstranit</th>
    </tr>
    <?php foreach ($uzivatele as $uzivatel) : ?>
    <tr>
        <td><?=$uzivatel['login'] ?></td>
        <td><?=$uzivatel['jmeno'] ?></td>
        <td><?=$uzivatel['prijmeni'] ?></td>
        <td><?=$uzivatel['email'] ?></td>
        <td><?php if($uzivatel['admin']){
            echo("Administrátor");
        } else if($uzivatel['recenzent']){
            echo("Recenzent");
        } else { echo("autor");} ?></td>
        <td><a class="odsazeni" href="seznamuzivatelu/<?= $uzivatel['uzivatel_id'] ?>/odstranit"><button type="button" class="btn btn-primary">Odstranit</button></a></td>
    </tr>
<?php endforeach ?>
</table>