<h1>Změna Hesla</h1>

<form method="post">
    <label for="Heslo" class="d-block">Heslo:</label>
    <input type="password" id="Heslo" name="heslo" class="col-auto mb-4" required/>
    <label for="Heslo2" class="d-block">Heslo znovu:</label>
    <input type="password" id="Heslo2" name="heslo_znovu" class="col-auto mb-4" required/>
    <label for="Rok" class="d-block">Rok:</label>
    <input type="number" id="Rok" name="rok" class="col-auto mb-4" required/>
    <input type="submit" value="Změnit" class="btn btn-primary d-block mx-auto" />
</form>